name: Supabase Keep Alive

on:
  schedule:
 
    - cron: "0 10 * * *" 
 
  workflow_dispatch: 

jobs:
  ping-supabase:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: |
          curl -X GET 'https://mevhxywtpmwbgxpdanyp.supabase.co/rest/v1/documents?select=*&limit=1' \
          -H 'apikey: ${{ secrets.SUPABASE_ANON_KEY }}' \
          -H 'Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}'
